site_name: Automation Notes
site_url: https://Play-Wright-course.github.io/automation-testing/
use_directory_urls: true
nav:
  - JavaScript Concepts:
      - RoadMap: javascriptConcepts/30-day-roadmap.md
      - "Synchronous & ASynchronous":
        -  concepts: javascriptConcepts/Synchronous-And-Asynchronous.md 
        -  deep guide: javascriptConcepts/Synchronous-vs-Asynchronous-deep-guide.md
      - Data Types: javascriptConcepts/dataTypes.md
      - Variables: javascriptConcepts/variables.md
      - Var vs Let: javascriptConcepts/var-vs-let-vaiable.md
      - Vaiables snipped code: javascriptConcepts/variables-code.md
      - Operator: javascriptConcepts/operator.md
      - Objects in JS: javascriptConcepts/objects-in-js.md
      - Flow Statements: javascriptConcepts/flow-statement.md
      - Arrays & Objects: javascriptConcepts/Arrays.md
      - String in JS: javascriptConcepts/string -in-js.md
      - Class & Constructor: javascriptConcepts/class-constructor.md
      - Functions: javascriptConcepts/functions.md
      - Arrow Functions: javascriptConcepts/arrow-functions.md
      - Regular Function vs Arrow Function: javascriptConcepts/regularfunction-vs-arrowFunction.md
      - JavaScript Promises: javascriptConcepts/js-promises.md
      - JavaScript Promises â€“ Snippet Code: javascriptConcepts/js-promises-snipped-code.md
      - Interview code: javascriptConcepts/basics-interview-code.md
      
  - PlayWright with Javascript:
    - General: playwright/jscode/general.md
    - Test Package: playwright/jscode/test-package.md
    - Sample Playwright Test: playwright/jscode/sample-playwright-test.md
    - Page vs Browser: playwright/jscode/page-vs-browser.md
    - Locators: playwright/jscode/locators.md
    - Methods in Playwright: playwright/jscode/methods-in-playwright.md
    - SendKeys Command: playwright/jscode/sendkeys-command.md
    - Input Value & Text Content: playwright/jscode/inputValue&TextContent.md
    - Dropdown: playwright/jscode/dropdown.md
    - Auto Suggestion Dropdown: playwright/jscode/auto-suggestion-dropdown.md
    - Radio Buttons: playwright/jscode/radio-buttons.md
    - Alert & Iframe: playwright/jscode/alert-iframe.md
    - Window & Tab Handle: playwright/jscode/window-tab-handle.md
    - Calendar: playwright/jscode/calender.md
    - Playwright Assertions: playwright/jscode/playwright-assertion.md
    - JSON Data Iteration: playwright/jscode/json-data-iteration.md
    - Excel Handling: playwright/jscode/excel.md
    - Custom Fixture to Get Test Data: playwright/jscode/customeFixureToGetTestData.md
    
  - PlayWright With Java:
      - Locators: playwright-Java/locator.md
      - Page Navigation: playwright-Java/page-navigation-actions.md
      - Inputs And Buttons: playwright-Java/playwright-interaction.md
      - Checkbox And Radio buttons: playwright-Java/checkbox-radio-button.md
      - Dropdown Handling: playwright-Java/dropdown_handling.md
      - iframe: playwright-Java/iframes.md
      - Mouse Keyboard Actions: playwright-Java/mouse-keyboard-actions.md
      - Alerts: playwright-Java/alerts-promt.md
      - Handle Windows: playwright-Java/handling-windows.md
      - File upload And Download: playwright-Java/file-upload-download.md
      - ScreenShot: playwright-Java/screenshot.md
      - Exceptions: playwright-Java/exceptions.md
      - InterViwe Questions: playwright-Java/interview-question.md

      

      
theme:
  name: material

markdown_extensions:
  - toc:
      permalink: true
  - tables
















